### ISSUE TITLE
Causes admin menu to disappear

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/collapsiblock#9]
I will try to find time to provide a better bug report later, but I'm pretty swamped right now. 

I will say that I added and enabled collapsiblock on a site with much content and other modules and it broke lots of things. There was a Javascript error, which I'll try to get later and share. 

Most noticiable was that the admin bar lost all menu items. The bar was still there, but the menu items not visible. 

Again, I will try to provide more details as soon as possible. I recognize that this is not enough info to act on, but maybe someone else will experience this problem and know they are not alone.

I was able to logout from the site, log back in and navigate to the modules page to disable collapsiblock and regain control of my site.

**Comment by stpaultim** [comment]
We looked at this together in Office Hours today and think that maybe there is a conflict with the custom JS in the sub-theme that I am using for this site. 

I will try to debug further ASAP.

**Comment by ericfoy** [comment]
I think I may have solved this issue today. After a bit of inspection I discovered the use of the now-deprecated function ".size()"

By editing the collapsiblock.js file, everything seems to work just fine now. There are two calls to `.size()` I simply replaced that text (two instances) with `.length` and everything's working.

Note that ".size()" must become ".length" -NOT- ".length()" because it's no longer a function call, but a simple attribute (if that's the right word —I'm not a js pro by any means!).
—Eric

**Comment by keiserjb** [comment]
I looked at the sites I'm using this on.  I could not replicate the problem in those sites but I did see the problem with a fresh install of Backdrop.

**Comment by laryn** [comment]
@keiserjb It probably relates to the version of jQuery in use. Your existing sites may be using the old/deprecated version, but new sites default to the newer version.

**Comment by keiserjb** [comment]
I changed it to jQuery 3 in an existing site and the menu doesn't go away.

**Comment by keiserjb** [comment]
I created a new release with these small js changes.  Thanks!
